name: dartboard
description: Retro Board made in dart
version: 0.0.1
#author: Jerold Albertson<jerold.albertson@gmail.com>
#homepage: https://github.com/jerold/DartBoard

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.2.0
  browser: ">=0.10.0 <0.11.0"
  firebase: any

dev_dependencies:
  build: ^0.4.0
  built_value_generator: ^0.4.3
  dart_to_js_script_rewriter: ^1.0.1
  test: any

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
